#!/usr/bin/env python3
"""Two-stage inference with ML-only Exploitability Gate v0.2.

This script is the runtime-facing entrypoint.  It extracts the same feature set
from a target evidence directory, loads the trained XGBoost Gate model, and
returns an exploit/no_exploit decision.  The Family Ranker can be attached after
this gate when the decision is exploit.
"""
import json
import csv
import os
import sys
import argparse
import numpy as np

try:
    import xgboost as xgb
    HAS_XGB = True
except ImportError:
    HAS_XGB = False

try:
    from sklearn.ensemble import GradientBoostingClassifier
    import pickle
except ImportError:
    pass

FEATURES = [
    "service_port",
    "is_http_target",
    "is_non_http_service",
    "raw_file_count",
    "tool_httpx_success",
    "tool_nuclei_success",
    "tool_metasploit_success",
    "metasploit_module_found",
    "version_in_vulnerable_range_true",
    "version_in_vulnerable_range_false",
    "version_not_affected",
    "version_patched",
    "precondition_pass_count",
    "precondition_fail_count",
    "negative_evidence_count",
    "auth_required",
    "no_auth_required",
    "endpoint_reachable_count",
    "endpoint_missing_count",
    "method_put_allowed",
    "method_put_rejected",
    "ajp_port_open",
    "ajp_port_closed",
    "anonymous_access",
    "velocity_enabled",
    "invokefunction_reachable",
    "invokefunction_not_found",
    "admin_party_enabled",
    "spring_detected",
    "spring_not_detected",
    "wrong_software_type",
    "rce_confirmed",
    "msf_check_confirmed",
    "msf_check_not_vulnerable",
    "nuclei_cve_confirmed",
    "nuclei_fingerprint_only",
    "nuclei_no_vuln_found",
    "manual_poc_failed",
    "painless_sandbox_blocks",
    "path_traversal_blocked",
    "auth_blocks_exploit",
    "endpoint_not_found",
    "wrong_version",
    "no_msf_module",
]

MODEL_PATH = "/home/kali/reports/dec-ml-only-gate-v02-2026-08-31/models/gate_xgb_v02.json"
DEFAULT_THRESHOLD = 0.20

def read_jsonl(filepath):
    """Load JSONL files generated by scanners, Metasploit, and custom probes."""
    if not os.path.exists(filepath):
        return []
    rows = []
    with open(filepath) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    rows.append(json.loads(line))
                except:
                    pass
    return rows

def read_raw(filepath):
    if not os.path.exists(filepath):
        return ""
    with open(filepath) as f:
        return f.read()

def detect_service_port(raw_dir, target_id):
    content = read_raw(os.path.join(raw_dir, "nmap.txt"))
    content += read_raw(os.path.join(raw_dir, "naabu.txt"))
    
    if "5984" in content: return 5984
    if "6379" in content: return 6379
    if "8081" in content: return 8081
    if "8080" in content: return 8080
    if "3000" in content: return 3000
    if "9200" in content: return 9200
    if "6800" in content: return 6800
    if "8009" in content: return 8009
    
    if "redis" in target_id: return 6379
    if "couchdb" in target_id: return 5984
    if "nexus" in target_id: return 8081
    if "jenkins" in target_id: return 8080
    if "grafana" in target_id: return 3000
    if "tomcat" in target_id: return 8080
    if "elasticsearch" in target_id: return 9200
    if "solr" in target_id: return 8983
    if "aria2" in target_id: return 6800
    if "nginx" in target_id: return 80
    if "shiro" in target_id: return 8080
    if "thinkphp" in target_id: return 80
    if "struts2" in target_id: return 8080
    if "flask" in target_id: return 5000
    if "phpmyadmin" in target_id: return 8080
    
    return 0

def extract_features(evidence_dir, target_id=None):
    features = {f: 0 for f in FEATURES}
    raw_dir = os.path.join(evidence_dir, "raw")
    
    if not target_id:
        target_id = os.path.basename(evidence_dir.rstrip("/"))
    
    # raw_file_count
    if os.path.isdir(raw_dir):
        features["raw_file_count"] = len([f for f in os.listdir(raw_dir) if os.path.isfile(os.path.join(raw_dir, f))])
    
    # Service port
    port = detect_service_port(raw_dir, target_id) if os.path.isdir(raw_dir) else 0
    features["service_port"] = port
    features["is_http_target"] = 1 if port in [80, 443, 8080, 8081, 3000, 8983, 5984] else 0
    features["is_non_http_service"] = 1 if port in [6379, 3306, 5432, 6800] else 0
    
    # Tool applicability
    for row in read_jsonl(os.path.join(evidence_dir, "tool-applicability.jsonl")):
        tool = row.get("tool_name", "")
        if tool == "httpx-toolkit" and row.get("status") == "success":
            features["tool_httpx_success"] = 1
        if tool == "nuclei" and row.get("status") == "success":
            features["tool_nuclei_success"] = 1
        if "metasploit" in tool and row.get("status") == "success":
            features["tool_metasploit_success"] = 1
    
    # Metasploit validation
    for row in read_jsonl(os.path.join(evidence_dir, "metasploit-validation.jsonl")):
        if row.get("module_found"):
            features["metasploit_module_found"] = 1
        if row.get("check_result") == "vulnerable":
            features["msf_check_confirmed"] = 1
        if row.get("check_result") == "not_vulnerable":
            features["msf_check_not_vulnerable"] = 1
        if not row.get("module_found"):
            features["no_msf_module"] = 1
    
    # Gate feature evidence
    for row in read_jsonl(os.path.join(evidence_dir, "gate-feature-evidence.jsonl")):
        fg = row.get("feature_group", "")
        feat = row.get("feature", "")
        val = row.get("value", False)
        
        # Version features
        if feat == "version_in_vulnerable_range" and val:
            features["version_in_vulnerable_range_true"] = 1
        elif feat == "version_in_vulnerable_range" and not val:
            features["version_in_vulnerable_range_false"] = 1
        if feat == "version_not_affected" and val:
            features["version_not_affected"] = 1
        if feat == "version_patched" and val:
            features["version_patched"] = 1
        
        # Precondition features
        if fg == "precondition":
            if val:
                features["precondition_pass_count"] += 1
            else:
                features["precondition_fail_count"] += 1
        
        # Negative evidence count
        if fg == "negative_evidence":
            features["negative_evidence_count"] += 1
        
        # Auth
        if feat == "no_auth_required" and val: features["no_auth_required"] = 1
        if feat == "auth_required" and val: features["auth_required"] = 1
        if feat == "auth_blocks_exploit" and val: features["auth_blocks_exploit"] = 1
        
        # Endpoint
        if feat == "anonymous_access" and val: features["anonymous_access"] = 1
        if feat == "endpoint_reachable" and val: features["endpoint_reachable_count"] += 1
        if feat == "endpoint_missing" and val: features["endpoint_missing_count"] += 1
        if feat == "endpoint_not_found" and val: features["endpoint_not_found"] = 1
        
        # Specific features
        if feat == "velocity_enabled" and val: features["velocity_enabled"] = 1
        if feat == "invokefunction_reachable" and val: features["invokefunction_reachable"] = 1
        if feat == "invokefunction_not_found" and val: features["invokefunction_not_found"] = 1
        if feat == "admin_party_enabled" and val: features["admin_party_enabled"] = 1
        if feat == "ajp_port_open" and val: features["ajp_port_open"] = 1
        if feat == "ajp_port_closed" and val: features["ajp_port_closed"] = 1
        if feat == "spring_detected" and val: features["spring_detected"] = 1
        if feat == "spring_not_detected" and val: features["spring_not_detected"] = 1
        if feat == "wrong_software_type" and val: features["wrong_software_type"] = 1
        if feat == "wrong_version" and val: features["wrong_version"] = 1
        if feat == "method_put_rejected" and val: features["method_put_rejected"] = 1
        if feat == "method_put_allowed" and val: features["method_put_allowed"] = 1
        
        # Exploit confirmation
        if feat == "rce_confirmed" and val: features["rce_confirmed"] = 1
        
        # Scanner features
        if feat == "nuclei_cve_confirmed" and val: features["nuclei_cve_confirmed"] = 1
        if feat == "nuclei_fingerprint_only" and val: features["nuclei_fingerprint_only"] = 1
        if feat == "nuclei_no_vuln_found" and val: features["nuclei_no_vuln_found"] = 1
        if feat == "manual_poc_failed" and val: features["manual_poc_failed"] = 1
        
        # Metasploit
        if feat == "msf_check_confirmed" and val: features["msf_check_confirmed"] = 1
        if feat == "msf_check_not_vulnerable" and val: features["msf_check_not_vulnerable"] = 1
        
        # Specific vuln mechanisms
        if feat == "painless_sandbox_blocks" and val: features["painless_sandbox_blocks"] = 1
        if feat == "path_traversal_blocked" and val: features["path_traversal_blocked"] = 1
    
    return features

def load_model():
    if HAS_XGB:
        model = xgb.XGBClassifier()
        model.load_model(MODEL_PATH)
    else:
        with open(MODEL_PATH, "rb") as f:
            model = pickle.load(f)
    return model

def load_training_threshold():
    metrics_path = "/home/kali/reports/dec-ml-only-gate-v02-2026-08-31/gate-metrics.json"
    if os.path.exists(metrics_path):
        with open(metrics_path) as f:
            metrics = json.load(f)
        return metrics.get("best_threshold", DEFAULT_THRESHOLD)
    return DEFAULT_THRESHOLD

def get_reason_features(features, importance_threshold=0.01):
    importance_path = "/home/kali/reports/dec-ml-only-gate-v02-2026-08-31/derived/gate-feature-importance.csv"
    importance_map = {}
    if os.path.exists(importance_path):
        with open(importance_path) as f:
            reader = csv.DictReader(f)
            for row in reader:
                importance_map[row["feature"]] = float(row["importance"])
    
    reasons = []
    for feat, val in features.items():
        if val > 0 and importance_map.get(feat, 0) > importance_threshold:
            reasons.append((feat, val, importance_map.get(feat, 0)))
    
    reasons.sort(key=lambda x: -x[2])
    return reasons

def main():
    parser = argparse.ArgumentParser(description="ML-only Exploitability Gate v0.2")
    parser.add_argument("--evidence-dir", required=True, help="Target evidence directory")
    parser.add_argument("--top-k", type=int, default=5, help="Top-K family ranking")
    parser.add_argument("--threshold", type=float, default=None, help="Override threshold")
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    args = parser.parse_args()
    
    evidence_dir = args.evidence_dir
    if not os.path.isdir(evidence_dir):
        print(f"ERROR: Directory not found: {evidence_dir}")
        sys.exit(1)
    
    # Get target_id
    target_id = os.path.basename(evidence_dir.rstrip("/"))
    
    # Extract features
    features = extract_features(evidence_dir, target_id)
    
    # Load model
    model = load_model()
    
    # Predict
    X = np.array([[features[f] for f in FEATURES]])
    proba = float(model.predict_proba(X)[0][1])
    
    # Threshold
    threshold = args.threshold if args.threshold else load_training_threshold()
    decision = "exploit" if proba >= threshold else "no_exploit"
    
    # Reason features
    reasons = get_reason_features(features)
    
    # Get candidate families
    candidate_negative = read_jsonl(os.path.join(evidence_dir, "candidate-negative-evidence.jsonl"))
    families = [row.get("candidate_family", "unknown") for row in candidate_negative]
    if not families:
        parts = target_id.split("_")
        if len(parts) > 1:
            families = [parts[0]]
    
    # Build result
    result = {
        "target_id": target_id,
        "exploitability_score": round(proba, 4),
        "threshold": threshold,
        "decision": decision,
        "top_families": families[:args.top_k],
        "reason_features": [{"feature": r[0], "value": r[1], "importance": round(r[2], 4)} for r in reasons[:5]],
        "feature_vector": {f: features[f] for f in FEATURES if features[f] != 0},
    }
    
    if args.json:
        print(json.dumps(result, indent=2))
    else:
        print(f"=== ML-only Exploitability Gate v0.2 ===")
        print(f"Target: {target_id}")
        print(f"Score: {proba:.4f}")
        print(f"Threshold: {threshold}")
        print(f"Decision: {decision}")
        print(f"Top families: {', '.join(families[:args.top_k])}")
        print(f"\nReason features:")
        for r in reasons[:5]:
            print(f"  {r[0]}: {r[1]} (importance={r[2]:.4f})")
        print(f"\nActive features:")
        for f, v in sorted(features.items()):
            if v != 0:
                print(f"  {f}: {v}")

if __name__ == "__main__":
    main()
